config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :interests
    resources :groups
    resources :users
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :contact do
    resources :groups
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :default_user do
    resources :groups
    resources :events
    resources :interests
    resources :dashboard, only: [:index]
  end

  resources :users

  resources :interests, only: [:index, :show]

  resources :groups, only: [:index, :show]

  resources :events, only: [:index, :show]
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :zipcode, presence: true
  has_and_belongs_to_many :groups, -> { distinct }
  has_and_belongs_to_many :interests, -> { distinct }
  has_and_belongs_to_many :users, -> { distinct }

  def human_dates
    [self.start_date.strftime("%A, %d %b %Y"), self.end_date.strftime("%A, %d %b %Y")]
  end

  def human_times
    [self.start_time.strftime("%l:%m %p"), self.start_time.strftime("%l:%m %p")]
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  def index
    @admin = current_user
    @events = Event.all
  end

  def show
    redirect_to admin_events_path
  end

  def new
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "New event created!"
      redirect_to admin_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    if @event.save
      flash[:success] = "Interest updated!"
      redirect_to admin_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:success] = "Interest successfully deleted!"
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/contact/events_controller.rb
class Contact::EventsController < Contact::BaseController

  def index
    @contact_events = []
    groups = Group.where(contact: @contact)
    groups.each do |group|
      group.events.each do |event|
        @contact_events << event
      end
    end
    @contact_events.reject(&:blank?)
    @events = @contact.events
  end

  def show
    redirect_to contact_events_path
  end

  def new
    @event = Event.new()
  end

  def create
    @event = current_user.events.new(event_params)
    @event = Event.new(event_params)
    if @event.save
      @contact.events << @event
      flash[:success] = "New event created!"
      redirect_to contact_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if params[:event].nil?
      @contact.events << @event
      redirect_to contact_events_path
    else
      @event.update(event_params)
      if @event.save
        @contact.events << @event
        flash[:success] = "Event updated!"
        redirect_to contact_events_path
      else
        flash[:failure] = "Please enter attributes correctly."
        render :edit
      end
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:success] = "Event successfully deleted!"
    redirect_to contact_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/default_user/events_controller.rb
class DefaultUser::EventsController < DefaultUser::BaseController

  def index
    @events = @default_user.events
  end

  def show
    @event = @default_user.events.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @default_user.events << @event
    flash[:success] = "Event added to your list!"
    redirect_to default_user_events_path
  end

  def destroy
    event = @default_user.events.find(params[:id])
    @default_user.events.delete(event)
    flash[:success] = "Event successfully deleted!"
    redirect_to default_user_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/contact/events_helper.rb
module Contact::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event] do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name %><br/><br/>

  <%= f.label :description %><br/>
  <%= f.text_area :description %><br/><br/>

  <%= f.label :start_date %><br/>
  <%= f.date_field :start_date %><br/><br/>

  <%= f.label :end_date %><br/>
  <%= f.date_field :end_date %><br/><br/>

  <%= f.label :start_time %><br/>
  <%= f.time_field :start_time %><br/><br/>

  <%= f.label :end_time %><br/>
  <%= f.time_field :end_time %><br/><br/>

  <%= f.label :location %><br/>
  <%= f.text_field :location %><br/><br/>

  <%= f.label :zipcode %><br/>
  <%= f.number_field :zipcode %><br/><br/>

  <%= f.label :group %><br/>
  <%= f.fields_for :groups, @event.groups do |group| %>
    <%= f.collection_select :group_ids, Group.order(:name), :id, :name %>
  <% end %><br/><br/>

  <%= f.label :interests %><br/>
  <%= f.fields_for :interests, @event.interests do |interest| %>
    <%= f.collection_check_boxes :interest_ids, Interest.order(:name), :id, :name %>
  <% end %><br/><br/>

  <%= f.submit %>

<% end %>

app/views/admin/events/edit.html.erb
<h1>Edit <%= @event.name %></h1>

<%= render partial: "form" %>

app/views/admin/events/index.html.erb
<h1>Admin Events</h1>

<h4><%= link_to "Create New Event", new_admin_event_path %></h4>


<div class="row">
  <div class="col-md-12">

    <table class="table">

      <thead>
        <th>Name</th>
        <th>Primary Group</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Location</th>
        <th>Zipcode</th>
        <th>Top Interest</th>
        <th># Attendees</th>
      </thead>

      <tbody>
        <% @events.each do |event| %>
        <tr>
          <th scope="row"> <%= event.name %></th>
            <td> <%= link_to event.groups.first.name, admin_groups_path if event.groups.exists? %> </td>
            <td> <%= event.human_dates[0] %></td>
            <td> <%= event.human_dates[1] %></td>
            <td> <%= event.human_times[0] %></td>
            <td> <%= event.human_times[1] %></td>
            <td> <%= event.location %></td>
            <td> <%= event.zipcode %></td>
            <td> <%= link_to event.interests.first.name, admin_interests_path if event.interests.exists? %> </td>
            <td> <%= event.users.count if event.users.exists? %></td>
            <td> <%= link_to "Edit", edit_admin_event_path(event) %></td>
            <td> <%= link_to "Delete", admin_event_path(event), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>