config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :interests
    resources :groups
    resources :users
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :contact do
    resources :groups
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :default_user do
    resources :groups
    resources :events
    resources :interests
    resources :dashboard, only: [:index]
  end

  resources :users

  resources :interests, only: [:index, :show]

  resources :groups, only: [:index, :show]

  resources :events, only: [:index, :show]
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :zipcode, presence: true
  has_and_belongs_to_many :groups, -> { distinct }
  has_and_belongs_to_many :interests, -> { distinct }
  has_and_belongs_to_many :users, -> { distinct }

  def human_dates
    [self.start_date.strftime("%A, %d %b %Y"), self.end_date.strftime("%A, %d %b %Y")]
  end

  def human_times
    [self.start_time.strftime("%l:%m %p"), self.start_time.strftime("%l:%m %p")]
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  def index
    @admin = current_user
    @events = Event.all
  end

  def show
    redirect_to admin_events_path
  end

  def new
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "New event created!"
      redirect_to admin_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    if @event.save
      flash[:success] = "Interest updated!"
      redirect_to admin_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:success] = "Interest successfully deleted!"
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/contact/events_controller.rb
class Contact::EventsController < Contact::BaseController

  def index
    @contact_events = []
    groups = Group.where(contact: @contact)
    groups.each do |group|
      group.events.each do |event|
        @contact_events << event
      end
    end
    @contact_events.reject(&:blank?)
    @events = @contact.events
  end

  def show
    redirect_to contact_events_path
  end

  def new
    @event = Event.new()
  end

  def create
    @event = current_user.events.new(event_params)
    @event = Event.new(event_params)
    if @event.save
      @contact.events << @event
      flash[:success] = "New event created!"
      redirect_to contact_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if params[:event].nil?
      @contact.events << @event
      redirect_to contact_events_path
    else
      @event.update(event_params)
      if @event.save
        @contact.events << @event
        flash[:success] = "Event updated!"
        redirect_to contact_events_path
      else
        flash[:failure] = "Please enter attributes correctly."
        render :edit
      end
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:success] = "Event successfully deleted!"
    redirect_to contact_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/default_user/base_controller.rb
class DefaultUser::BaseController < ApplicationController
  before_action :require_default, :set_user

  def require_default
    flash[:notice] = "Please login to access your dashboard." unless current_default? || current_contact?
    redirect_to login_path unless current_default? || current_contact?
  end

  def set_user
    @default_user = current_user
  end

end

app/controllers/default_user/dashboard_controller.rb
class DefaultUser::DashboardController < DefaultUser::BaseController

  def index
    @user = current_user
  end

end

app/controllers/default_user/events_controller.rb
class DefaultUser::EventsController < DefaultUser::BaseController

  def index
    @events = @default_user.events
  end

  def show
    @event = @default_user.events.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @default_user.events << @event
    flash[:success] = "Event added to your list!"
    redirect_to default_user_events_path
  end

  def destroy
    event = @default_user.events.find(params[:id])
    @default_user.events.delete(event)
    flash[:success] = "Event successfully deleted!"
    redirect_to default_user_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/default_user/groups_controller.rb
class DefaultUser::GroupsController < DefaultUser::BaseController

  def current_user_contact(group)
    @default_user.update(role: 2)
    group.interests << Interest.find(group_params[:interest_ids].reject(&:blank?))
    @default_user.groups << group
  end

  def index
    @groups = @default_user.groups
  end

  def show
    redirect_to default_user_groups_path
  end

  def new
    @group = @default_user.groups.new()
  end

  def create
    group = Group.new(group_params)
    if group.save
      current_user_contact(group)
      flash[:success] = "New group created!"
      redirect_to contact_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def update
    group = Group.find(params[:id])
    @default_user.groups << group
    flash[:success] = "Group added to your list!"
    redirect_to default_user_groups_path if current_user.default?
    redirect_to contact_groups_path if current_user.contact?
  end

  def destroy
    group = @default_user.groups.find(params[:id])
    @default_user.groups.delete(group)
    flash[:success] = "Group successfully deleted!"
    redirect_to default_user_groups_path
  end

  private

  def group_params
    hash = params.require(:group).permit(:name, :description, interest_ids: [])
    hash[:contact] = @default_user
    hash
  end

end

app/controllers/default_user/interests_controller.rb
class DefaultUser::InterestsController < DefaultUser::BaseController

  def index
    @interests = @default_user.interests
  end

  def show
    redirect_to default_user_interests_path
  end

  def update
    interest = Interest.find(params[:id])
    @default_user.interests << interest
    flash[:success] = "Interest added to your list!"
    redirect_to default_user_interests_path
  end

  def destroy
    interest = @default_user.interests.find(params[:id])
    @default_user.interests.delete(interest)
    flash[:success] = "Interest successfully deleted!"
    redirect_to default_user_interests_path
  end

  private

  def interest_params
    params.require(:interest).permit(:name)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/contact/events_helper.rb
module Contact::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/default_user/events/index.html.erb
<h1>Your Events</h1><br/><br/>

<% if @events.empty? %>
  <h4>There's nothing here yet! <br/><br/><%= link_to "Events You May Like", events_path %></h4>
<% else %>


<div class="row">
  <div class="col-md-12">

    <table class="table">

      <thead>
        <th>Name</th>
        <th>Primary Group</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Location</th>
        <th>Zipcode</th>
        <th>Top Interest</th>
      </thead>

      <tbody>
        <% @events.each do |event| %>
        <tr>
          <th scope="row"> <%= event.name %></th>
            <td> <%= link_to event.groups.first.name, groups_path if event.groups.exists? %> </td>
            <td> <%= event.description %> </td>
            <td> <%= event.human_dates[0] %></td>
            <td> <%= event.human_times[0] %></td>
            <td> <%= event.human_times[1] %></td>
            <td> <%= event.location %></td>
            <td> <%= event.zipcode %></td>
            <td> <%= link_to event.interests.first.name, interests_path if event.interests.exists? %> </td>
            <td> <%= link_to "Delete", default_user_event_path(event), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

<% end %>

app/views/default_user/events/show.html.erb
<h1><%= @event.name %></h1>

<% if @event.groups.exists? %>
  <h3>with
    <% @event.groups.each do |group| %>
      <%= link_to group.name, group_path(group) %><br/>
    <% end %>
  </h3>
<% end %>

<div class="container text-center">
  <h3><strong>Description: </strong><%= @event.description %></h3>
  <h3><strong>Start Date: </strong><%= @event.human_dates[0] %></h3>
  <h3><strong>End Date: </strong><%= @event.human_dates[1] %></h3>
  <h3><strong>Start Time:</strong><%= @event.human_times[0] %></h3>
  <h3><strong>End Time:</strong><%= @event.human_times[1] %></h3>
  <h3><strong>Location: </strong><%= @event.location %></h3>
</div>

<h4> the group holding this event is interested in:
  <% @event.interests.each do |interest| %>
      <%= link_to interest.name, interest_path(interest) %>
  <% end %>
</h4>