config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :interests
    resources :groups
    resources :users
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :contact do
    resources :groups
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :default_user do
    resources :groups
    resources :events
    resources :interests
    resources :dashboard, only: [:index]
  end

  resources :users

  resources :interests, only: [:index, :show]

  resources :groups, only: [:index, :show]

  resources :events, only: [:index, :show]
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  has_and_belongs_to_many :interests, -> { distinct }
  has_and_belongs_to_many :events, -> { distinct }
  has_and_belongs_to_many :users, -> { distinct }
  belongs_to :contact, class_name: "User"
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController
  def index
    @admin = current_user
    @groups = Group.all
  end

  def show
    redirect_to admin_groups_path
  end

  def new
    @group = Group.new()
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = "New group created!"
      redirect_to admin_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    if @group.save
      flash[:success] = "Interest updated!"
      redirect_to admin_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :edit
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    flash[:success] = "Interest successfully deleted!"
    redirect_to admin_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :contact_id, :interest_ids)
  end
end

app/controllers/contact/groups_controller.rb
class Contact::GroupsController < Contact::BaseController

# Need to create two instance variables: one scoped off of groups for which user is a contact, and one for which user is just default
# Need to apply this logic to other contact controllers for when user changes from default to contact
# Then edit views so that user can only edit groups/events for which they're a contact once they change from default to contact
# Also need to give contact interests controller

  def index
    @contact_groups = Group.where(contact: @contact)
    @groups = @contact.groups.where.not(contact: @contact)
  end

  def show
    redirect_to contact_groups_path
  end

  def new
    @group = Group.new()
  end

  def create
    @group = Group.new(group_params)
    @group.contact = @contact
    if @group.save
      @group.interests << Interest.find(group_params[:interest_ids].reject(&:blank?))
      @contact.groups << @group
      flash[:success] = "New group created!"
      redirect_to contact_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @group = @contact.groups.find(params[:id])
  end

  def update
    @group = @contact.groups.find(params[:id])
    @group.update(group_params)
    if @group.save
      @contact.groups << @group
      flash[:success] = "Group updated!"
      redirect_to contact_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :edit
    end
  end

  def destroy
    group = @contact.groups.find(params[:id])
    @contact.groups.delete(group)
    group.destroy
    flash[:success] = "Group successfully deleted!"
    redirect_to contact_groups_path
  end

  private

  def group_params
    hash = params.require(:group).permit(:name, :description, interest_ids: [])
  end
end

app/controllers/default_user/groups_controller.rb
class DefaultUser::GroupsController < DefaultUser::BaseController

  def current_user_contact(group)
    @default_user.update(role: 2)
    group.interests << Interest.find(group_params[:interest_ids].reject(&:blank?))
    @default_user.groups << group
  end

  def index
    @groups = @default_user.groups
  end

  def show
    redirect_to default_user_groups_path
  end

  def new
    @group = @default_user.groups.new()
  end

  def create
    group = Group.new(group_params)
    if group.save
      current_user_contact(group)
      flash[:success] = "New group created!"
      redirect_to contact_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def update
    group = Group.find(params[:id])
    @default_user.groups << group
    flash[:success] = "Group added to your list!"
    redirect_to default_user_groups_path if current_user.default?
    redirect_to contact_groups_path if current_user.contact?
  end

  def destroy
    group = @default_user.groups.find(params[:id])
    @default_user.groups.delete(group)
    flash[:success] = "Group successfully deleted!"
    redirect_to default_user_groups_path
  end

  private

  def group_params
    hash = params.require(:group).permit(:name, :description, interest_ids: [])
    hash[:contact] = @default_user
    hash
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/contact/groups_helper.rb
module Contact::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<h1>All Groups</h1>

<h4><%= link_to "Create New Group", new_default_user_group_path %></h4><br/><br/>

<div class="row">
  <div class="col-md-12">

    <table class="table">

<!-- Change table to have first upcoming event for group instead of event count -->

      <thead>
        <th>Group</th>
        <th>Event Count</th>
        <th>Top Interest</th>
      </thead>

      <tbody>
        <% @groups.each do |group| %>
        <tr>
          <th scope="row"> <%= link_to group.name, group_path(group) %></th>
            <td> <%= group.events.count %></td>
            <td> <%= link_to group.interests.first.name, interest_path(group.interests.first) if group.interests.exists? %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<h3>Interests:
  <% @group.interests.each do |interest| %>
    <%= link_to interest.name, interest_path(interest) %>
  <% end %>
</h3>

<div class="container">
    <h3>Events</h3>
    <table class="table">
      <tbody>
        <% @group.events.each do |event| %>
          <tr>
            <th scope="row" class="text-center"><%= link_to event.name, event_path(event) %> - <%= event.human_dates[0] %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<% if current_user && current_user.default? %>
  <h3> <%= link_to "Add to Your Groups", default_user_group_path(@group), method: :put %></h3>
<% elsif current_user && current_user.contact? %>
  <h3> <%= link_to "Add to Your Groups", default_user_group_path(@group), method: :put %></h3>
<% else %>
  <h3> <%= link_to "Login to RSVP", login_path %> </h3>
<% end %>