config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :interests
    resources :groups
    resources :users
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :contact do
    resources :groups
    resources :events
    resources :dashboard, only: [:index]
  end

  namespace :default_user do
    resources :groups
    resources :events
    resources :interests
    resources :dashboard, only: [:index]
  end

  resources :users

  resources :interests, only: [:index, :show]

  resources :groups, only: [:index, :show]

  resources :events, only: [:index, :show]
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :location, presence: true
  validates :zipcode, presence: true
  has_and_belongs_to_many :groups, -> { distinct }
  has_and_belongs_to_many :interests, -> { distinct }
  has_and_belongs_to_many :users, -> { distinct }

  def human_dates
    [self.start_date.strftime("%A, %d %b %Y"), self.end_date.strftime("%A, %d %b %Y")]
  end

  def human_times
    [self.start_time.strftime("%l:%m %p"), self.start_time.strftime("%l:%m %p")]
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  def index
    @admin = current_user
    @events = Event.all
  end

  def show
    redirect_to admin_events_path
  end

  def new
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "New event created!"
      redirect_to admin_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    if @event.save
      flash[:success] = "Interest updated!"
      redirect_to admin_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:success] = "Interest successfully deleted!"
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/contact/base_controller.rb
class Contact::BaseController < ApplicationController
  before_action :require_contact, :set_contact

  def require_contact
    flash[:notice] = "Please log in as a contact to update groups or events." unless current_contact?
    redirect_to login_path unless current_contact?
  end

  def set_contact
    @contact = current_user
  end
end

app/controllers/contact/dashboard_controller.rb
class Contact::DashboardController < Contact::BaseController

  def index
    @contact = current_user
  end

end

app/controllers/contact/events_controller.rb
class Contact::EventsController < Contact::BaseController

  def index
    @contact_events = []
    groups = Group.where(contact: @contact)
    groups.each do |group|
      group.events.each do |event|
        @contact_events << event
      end
    end
    @contact_events.reject(&:blank?)
    @events = @contact.events
  end

  def show
    redirect_to contact_events_path
  end

  def new
    @event = Event.new()
  end

  def create
    @event = current_user.events.new(event_params)
    @event = Event.new(event_params)
    if @event.save
      @contact.events << @event
      flash[:success] = "New event created!"
      redirect_to contact_events_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if params[:event].nil?
      @contact.events << @event
      redirect_to contact_events_path
    else
      @event.update(event_params)
      if @event.save
        @contact.events << @event
        flash[:success] = "Event updated!"
        redirect_to contact_events_path
      else
        flash[:failure] = "Please enter attributes correctly."
        render :edit
      end
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    flash[:success] = "Event successfully deleted!"
    redirect_to contact_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/contact/groups_controller.rb
class Contact::GroupsController < Contact::BaseController

# Need to create two instance variables: one scoped off of groups for which user is a contact, and one for which user is just default
# Need to apply this logic to other contact controllers for when user changes from default to contact
# Then edit views so that user can only edit groups/events for which they're a contact once they change from default to contact
# Also need to give contact interests controller

  def index
    @contact_groups = Group.where(contact: @contact)
    @groups = @contact.groups.where.not(contact: @contact)
  end

  def show
    redirect_to contact_groups_path
  end

  def new
    @group = Group.new()
  end

  def create
    @group = Group.new(group_params)
    @group.contact = @contact
    if @group.save
      @group.interests << Interest.find(group_params[:interest_ids].reject(&:blank?))
      @contact.groups << @group
      flash[:success] = "New group created!"
      redirect_to contact_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :new
    end
  end

  def edit
    @group = @contact.groups.find(params[:id])
  end

  def update
    @group = @contact.groups.find(params[:id])
    @group.update(group_params)
    if @group.save
      @contact.groups << @group
      flash[:success] = "Group updated!"
      redirect_to contact_groups_path
    else
      flash[:failure] = "Please enter attributes correctly."
      render :edit
    end
  end

  def destroy
    group = @contact.groups.find(params[:id])
    @contact.groups.delete(group)
    group.destroy
    flash[:success] = "Group successfully deleted!"
    redirect_to contact_groups_path
  end

  private

  def group_params
    hash = params.require(:group).permit(:name, :description, interest_ids: [])
  end
end

app/controllers/default_user/events_controller.rb
class DefaultUser::EventsController < DefaultUser::BaseController

  def index
    @events = @default_user.events
  end

  def show
    @event = @default_user.events.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @default_user.events << @event
    flash[:success] = "Event added to your list!"
    redirect_to default_user_events_path
  end

  def destroy
    event = @default_user.events.find(params[:id])
    @default_user.events.delete(event)
    flash[:success] = "Event successfully deleted!"
    redirect_to default_user_events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :start_time, :end_time, :location, :zipcode, :group_ids, :interest_ids)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/contact/base_helper.rb
module Contact::BaseHelper
end

app/helpers/contact/events_helper.rb
module Contact::EventsHelper
end

app/helpers/contact/groups_helper.rb
module Contact::GroupsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/contact/events/_form.html.erb
<%= form_for [:contact, @event] do |f| %>
<%= f.label :name %><br/>
<%= f.text_field :name %><br/><br/>

<%= f.label :description %><br/>
<%= f.text_area :description %><br/><br/>

<%= f.label :start_date %><br/>
<%= f.date_field :start_date %><br/><br/>

<%= f.label :end_date %><br/>
<%= f.date_field :end_date %><br/><br/>

<%= f.label :start_time %><br/>
<%= f.time_field :start_time %><br/><br/>

<%= f.label :end_time %><br/>
<%= f.time_field :end_time %><br/><br/>

<%= f.label :location %><br/>
<%= f.text_field :location %><br/><br/>

<%= f.label :zipcode %><br/>
<%= f.number_field :zipcode %><br/><br/>

<%= f.label :group %><br/>
<%= f.fields_for :groups, @event.groups do |group| %>
  <%= f.collection_select :group_ids, Group.where(contact: @contact).order(:name), :id, :name %>
<% end %><br/><br/>

<%= f.label :interests %><br/>
<%= f.fields_for :interests, @event.interests do |interest| %>
  <%= f.collection_check_boxes :interest_ids, Interest.order(:name), :id, :name %>
<% end %><br/><br/>

<%= f.submit %>
<% end %>

app/views/contact/events/edit.html.erb
<h1>Edit <%= @event.name %></h1>

<%= render partial: "form" %>

app/views/contact/events/index.html.erb
<h1>Your Events as a Contact</h1>

<h4> <%= link_to "Create New Event", new_contact_event_path %> </h4>

<div class="row">
  <div class="col-md-12">

    <table class="table">

      <thead>
        <th>Name</th>
        <th>Primary Group</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Location</th>
        <th>Zipcode</th>
        <th>Top Interest</th>
        <th># Attending</th>
      </thead>

      <tbody>
        <% @contact_events.each do |event| %>
        <tr>
          <th scope="row"> <%= event.name %></th>
            <td> <%= link_to event.groups.first.name, groups_path if event.groups.exists? %> </td>
            <td> <%= event.description %> </td>
            <td> <%= event.human_dates[0] %></td>
            <td> <%= event.human_times[0] %></td>
            <td> <%= event.human_times[1] %></td>
            <td> <%= event.location %></td>
            <td> <%= event.zipcode %></td>
            <td> <%= link_to event.interests.first.name, interests_path if event.interests.exists? %> </td>
            <td> <%= event.users.count if event.users.exists? %></td>
            <td> <%= link_to "Edit", edit_contact_event_path(event) %></td>
            <td> <%= link_to "Delete", contact_event_path(event), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

<br/>
<br/>
<br/>

<h1>Events You Just Like</h1>

<div class="row">
  <div class="col-md-12">

    <table class="table">

      <thead>
        <th>Name</th>
        <th>Primary Group</th>
        <th>Description</th>
        <th>Start Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Location</th>
        <th>Zipcode</th>
        <th>Top Interest</th>
        <th># Attending</th>
      </thead>

      <tbody>
        <% @events.each do |event| %>
        <tr>
          <th scope="row"> <%= event.name %></th>
            <td> <%= link_to event.groups.first.name, groups_path if event.groups.exists? %> </td>
            <td> <%= event.description %> </td>
            <td> <%= event.human_dates[0] %></td>
            <td> <%= event.human_times[0] %></td>
            <td> <%= event.human_times[1] %></td>
            <td> <%= event.location %></td>
            <td> <%= event.zipcode %></td>
            <td> <%= link_to event.interests.first.name, interests_path if event.interests.exists? %> </td>
            <td> <%= event.users.count if event.users.exists? %></td>
            <td> <%= link_to "Edit", edit_contact_event_path(event) %></td>
            <td> <%= link_to "Delete", contact_event_path(event), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/contact/events/new.html.erb
<h1>Create New Event</h1>

<%= render partial: "form" %>